### ISSUE TITLE
Crash with SMMA and one-element arrays

### ISSUE THREAD

**Issue by brauliobo** [bradcater/moving_averages#1]
This will crash
```
[1].smma
```

**Comment by bradcater** [comment]
What should it return? `1`?

In the meantime, I've added tests for the single-element case.

**Comment by brauliobo** [comment]
Yes, just like `ema`, `wma` and `sma`

**Comment by brauliobo** [comment]
Also, all functions crash with empty arrays. It would be better to return nil instead

**Comment by bradcater** [comment]
I've fixed the single-element and empty Array cases in 5644d71e9c73c818d0fe97c6404bb8c22e98dd1f and 08ea6ed9b651f494984a0eb7227d7b03b363d5cf, respectively.

**Comment by brauliobo** [comment]
Tranks @bradcater !
